name: Continuous Integrations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory : "./cse364-project"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create mongoDB container      
        run: sudo docker run -d -p 27017:27017 mongo:latest


      - name: build mvn
        run: mvn -B package --file pom.xml

      - name: Run mvn test
        run: mvn test
